language: scala
sudo: false
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt/launchers
dist: xenial
jdk: openjdk8
script:
- sbt ++$TRAVIS_SCALA_VERSION test
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
scala:
- 2.13.0
- 2.12.8
- 2.11.12
